In [1]:
import numpy as np

In [2]:
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

In [3]:
np.add(first_array, second_array)

array([ 3,  7, 11, 15])

In [6]:
first_array * second_array

array([ 2, 12, 30, 56])

In [9]:
numbers = np.array([1.23456, 2.34567, 3.45678, 4.56789])

np.round(numbers,2)

array([1.23, 2.35, 3.46, 4.57])

In [10]:
grades = np.array([76, 78, 81, 66, 85])

In [11]:
np.mean(grades)

77.2

In [12]:
array1 = np.array([[1, 3], 
                   [5, 7],
                   [6, 4]])

In [13]:
np.mean(array1)

4.0

In [14]:
np.mean(a=array1,axis=0)

array([3., 5.])

In [15]:
np.mean(a=array1, axis=1)

array([2., 6.])